[package]
name = "modbus-frames"
version = "0.1.0"
authors = ["JC <joshcrawfy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc16 = "0.4"
